const ActionType = {
  // Movies
  SET_MOVIES: 'SET_MOVIES',
  SET_FILTRED_MOVIES: 'SET_FILTRED_MOVIES',
  FETCH_MOVIES: 'FETCH_MOVIES',
  LIKE_MOVIE: 'LIKE_MOVIE',
  DESLIKE_MOVIE: 'DESLIKE_MOVIE',
  DELETE_MOVIE: 'DELETE_MOVIE',
  ADD_MOVIE: 'ADD_MOVIE',
  UPDATE_MOVIE: 'UPDATE_MOVIE',
  // Pagination
  SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
  SET_PER_PAGE: 'SET_PER_PAGE',
};
export default ActionType;
