const ActionType = {
  // Movies
  SET_MOVIES: 'SET_MOVIES',
  FETCH_MOVIES: 'FETCH_MOVIES',
  LIKE_MOVIE: 'LIKE_MOVIE',
  DESLIKE_MOVIE: 'DESLIKE_MOVIE',
  DELETE_MOVIE: 'DELETE_MOVIE',
  ADD_MOVIE: 'ADD_MOVIE',
  UPDATE_MOVIE: 'UPDATE_MOVIE',
};
export default ActionType;
